version: 0.2

env:
  secrets-manager:
    ssh_key: arn:aws:secretsmanager:us-east-1:455667379642:secret:gh-deploy-ssh-key-2adter:gh_id_rsa
    ssh_pub: arn:aws:secretsmanager:us-east-1:455667379642:secret:gh-deploy-ssh-key-2adter:gh_id_rsa_pub
    git_url: git@github.com:GreyHelixIO/GH-Deploy.git
    TF_VAR_AWS_ID: arn:aws:secretsmanager:us-east-1:455667379642:secret:gh-global-terraform-SgEFp1:AWS_ID
    TF_VAR_AWS_SECRET: arn:aws:secretsmanager:us-east-1:455667379642:secret:gh-global-terraform-SgEFp1:AWS_SECRET

phases:
  install:
    commands:
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform

  pre-build:
    commands:
      - mkdir -p ~/.ssh
      - echo "$ssh_key" > ~/.ssh/id_rsa
      - echo "$ssh_pub" > ~/.ssh/id_rsa.pub
      - chmod 600 ~/.ssh/id_rsa
      - eval "$(ssh-agent -s)"
      - git init
      - git remote add origin "$git_url"
      - git fetch origin
      - git branch
      - git checkout -f "$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - git submodule init
      - git submodule update --recursive

  build:
    commands:
      - cd ./tf/global
      - terraform init
      - terraform apply -auto-approve